default: &default
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1

test: &test
  <<: *default
  database: multi_db_test

test_slave_database_1:
  <<: *test

test_slave_database_2:
  <<: *test
  weight: 10
  
test_slave_database_3:
  <<: *test
  weight: 0

test_slave_database_4:
  <<: *test
  weight: 5

test_extra: &test_extra
  <<: *default
  database: multi_db_test_extra

test_extra_slave_database_1:
  <<: *test_extra

test_extra_slave_database_2:
  <<: *test_extra

readable_master:
  <<: *default
  database: multi_db_readable_master
  readable: true

readable_master_slave_database:
  <<: *default
  database: multi_db_readable_master

unused:
  <<: *test

unused_slave_database:
  <<: *test
